### ISSUE TITLE
Port to lazarus

### ISSUE THREAD

**Issue by s1nka** [drapid/rnq#1]
После портирования в Lazarus/FPS можно получить:
- Мультиплатформенную программу. Линуксойды шлют привет.
- Не нужно будет воровать Delphi(у бедных студентов нет денег на лицензионный Delphi). Опять же Линуксойды будут рады собирать под своими линуксами R&Q.
- Поддержка свободного ПО.
- Легкость сборки под одной ОС сразу пакеты под разные ОС.

**Comment by sunsell** [comment]
Был уже прототип. Ненужен никому.
